version: '3.8'

services:

  db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [CMD-SHELL, pg_isready -h localhost -p 5432]
      interval: 10s
      timeout: 5s
      retries: 5
    mem_limit: 8g
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    user: postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/final_project?sslmode=disable
    networks:
      - app-network
    restart: always

volumes:
  postgres_data:
networks:
  app-network: