version: "3.8"

services:
  postgres:
    image: "postgres:16"
    networks:
      new:
        aliases:
          - postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_migrations
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  migrate:
    image: migrate/migrate
    networks:
      - new
    volumes:
      - ./db/migration:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:postgres@postgres:5432/final_project?sslmode=disable",
        "up",
        "3",
      ]
    depends_on:
      - postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - new
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable

networks:
  new:

volumes:
  postgres_data:
