// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Serializable is an autogenerated mock type for the Serializable type
type Serializable struct {
	mock.Mock
}

type Serializable_Expecter struct {
	mock *mock.Mock
}

func (_m *Serializable) EXPECT() *Serializable_Expecter {
	return &Serializable_Expecter{mock: &_m.Mock}
}

// Serialize provides a mock function with given fields:
func (_m *Serializable) Serialize() ([]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Serialize")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Serializable_Serialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Serialize'
type Serializable_Serialize_Call struct {
	*mock.Call
}

// Serialize is a helper method to define mock.On call
func (_e *Serializable_Expecter) Serialize() *Serializable_Serialize_Call {
	return &Serializable_Serialize_Call{Call: _e.mock.On("Serialize")}
}

func (_c *Serializable_Serialize_Call) Run(run func()) *Serializable_Serialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Serializable_Serialize_Call) Return(_a0 []byte, _a1 error) *Serializable_Serialize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Serializable_Serialize_Call) RunAndReturn(run func() ([]byte, error)) *Serializable_Serialize_Call {
	_c.Call.Return(run)
	return _c
}

// NewSerializable creates a new instance of Serializable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSerializable(t interface {
	mock.TestingT
	Cleanup(func())
}) *Serializable {
	mock := &Serializable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
